package com.pein.teacher.respository;

import com.pein.teacher.domain.tsOcr;

public interface tsOcrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int insert(tsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int insertSelective(tsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    tsOcr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(tsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(tsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(tsOcr record);
}