package com.pein.teacher.respository;

import com.pein.teacher.domain.tsUser;

public interface tsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int insert(tsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int insertSelective(tsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    tsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(tsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(tsUser record);
}