package com.pein.teacher.domain;

import java.util.Date;

public class tsOcr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.p_origin_path
     *
     * @mbggenerated
     */
    private String pOriginPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.p_dest_path
     *
     * @mbggenerated
     */
    private String pDestPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_ocr.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.id
     *
     * @return the value of ts_ocr.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.id
     *
     * @param id the value for ts_ocr.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.p_origin_path
     *
     * @return the value of ts_ocr.p_origin_path
     *
     * @mbggenerated
     */
    public String getpOriginPath() {
        return pOriginPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.p_origin_path
     *
     * @param pOriginPath the value for ts_ocr.p_origin_path
     *
     * @mbggenerated
     */
    public void setpOriginPath(String pOriginPath) {
        this.pOriginPath = pOriginPath == null ? null : pOriginPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.p_dest_path
     *
     * @return the value of ts_ocr.p_dest_path
     *
     * @mbggenerated
     */
    public String getpDestPath() {
        return pDestPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.p_dest_path
     *
     * @param pDestPath the value for ts_ocr.p_dest_path
     *
     * @mbggenerated
     */
    public void setpDestPath(String pDestPath) {
        this.pDestPath = pDestPath == null ? null : pDestPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.user_id
     *
     * @return the value of ts_ocr.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.user_id
     *
     * @param userId the value for ts_ocr.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.create_time
     *
     * @return the value of ts_ocr.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.create_time
     *
     * @param createTime the value for ts_ocr.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.update_time
     *
     * @return the value of ts_ocr.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.update_time
     *
     * @param updateTime the value for ts_ocr.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_ocr.content
     *
     * @return the value of ts_ocr.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_ocr.content
     *
     * @param content the value for ts_ocr.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}