package com.pein.teacher.repository;


import com.pein.teacher.domain.TsOcr;

import java.util.List;

public interface TsOcrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int insert(TsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int insertSelective(TsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    TsOcr selectByPrimaryKey(Integer id);


    List<TsOcr> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TsOcr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_ocr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsOcr record);
}