package com.pein.teacher.repository;

import com.pein.teacher.domain.TsUser;


public interface TsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int insert(TsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int insertSelective(TsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    TsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TsUser record);
}